parameters:
    ezsettings.default.content_edit.templates.edit: '@@IbexaContentForms/Content/content_edit.html.twig'
    ezsettings.default.content_edit.templates.create: '@@IbexaContentForms/Content/content_edit.html.twig'
    ezsettings.default.content_edit.templates.create_draft: '@@IbexaContentForms/Content/content_create_draft.html.twig'

    ezsettings.default.user_edit.templates.update: '@@IbexaContentForms/Content/content_edit.html.twig'
    ezsettings.default.user_edit.templates.create: '@@IbexaContentForms/Content/content_edit.html.twig'

    ezsettings.default.content_edit_view: {}
    ezsettings.default.content_create_view: {}
