parameters:
    ibexa.site_access.config.default.content_edit.templates.edit: '@@IbexaContentForms/Content/content_edit.html.twig'
    ibexa.site_access.config.default.content_edit.templates.create: '@@IbexaContentForms/Content/content_edit.html.twig'
    ibexa.site_access.config.default.content_edit.templates.create_draft: '@@IbexaContentForms/Content/content_create_draft.html.twig'

    ibexa.site_access.config.default.user_edit.templates.update: '@@IbexaContentForms/Content/content_edit.html.twig'
    ibexa.site_access.config.default.user_edit.templates.create: '@@IbexaContentForms/Content/content_edit.html.twig'

    ibexa.site_access.config.default.content_edit_view: {}
    ibexa.site_access.config.default.content_create_view: {}
