services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Ibexa\ContentForms\Behat\Context\ContentTypeContext:
        arguments:
            $permissionResolver: '@=service("ibexa.api.repository").getPermissionResolver()'
            $contentTypeService: '@ibexa.api.service.content_type'

    Ibexa\ContentForms\Behat\Context\PagelayoutContext:
        arguments:
            $configResolver: '@ibexa.config.resolver'

    Ibexa\ContentForms\Behat\Context\UserRegistrationContext:
        arguments:
            $permissionResolver: '@=service("ibexa.api.repository").getPermissionResolver()'
            $roleService: '@ibexa.api.service.role'
            $userService: '@ibexa.api.service.user'
            $contentTypeService: '@ibexa.api.service.content_type'
