imports:
    - {resource: fieldtypes.yaml}
    - {resource: form_types.yaml}
    - {resource: views.yaml}

parameters:
    ezplatform.content_forms.field_type_form_mapper.dispatcher.class: Ibexa\ContentForms\FieldType\FieldTypeFormMapperDispatcher
    ezplatform.content_forms.field.form_type.class: Ibexa\ContentForms\Form\Type\Content\ContentFieldType

    ezplatform.content_forms.validator.field_value.class: Ibexa\ContentForms\Validator\Constraints\FieldValueValidator

    ezplatform.content_forms.action_dispatcher.base.class: Ibexa\ContentForms\Form\ActionDispatcher\AbstractActionDispatcher
    ezplatform.content_forms.action_dispatcher.content.class: Ibexa\ContentForms\Form\ActionDispatcher\ContentDispatcher
    ezplatform.content_forms.action_dispatcher.user.class: Ibexa\ContentForms\Form\ActionDispatcher\UserDispatcher
    ezplatform.content_forms.form_processor.content.class: Ibexa\ContentForms\Form\Processor\ContentFormProcessor
    ezplatform.content_forms.form_processor.user_create.class: Ibexa\ContentForms\Form\Processor\User\UserCreateFormProcessor
    ezplatform.content_forms.form_processor.user_update.class: Ibexa\ContentForms\Form\Processor\User\UserUpdateFormProcessor
    ezplatform.content_forms.form_processor.user_cancel.class: Ibexa\ContentForms\Form\Processor\User\UserCancelFormProcessor

    ezplatform.content_forms.controller.content_edit.class: Ibexa\Bundle\ContentForms\Controller\ContentEditController
    ezplatform.content_forms.controller.user_register.class: Ibexa\Bundle\ContentForms\Controller\UserRegisterController
    ezplatform.content_forms.controller.user.class: Ibexa\Bundle\ContentForms\Controller\UserController

    ezplatform.content_forms.view_templates_listener.class: Ibexa\ContentForms\EventListener\ViewTemplatesListener

    ezplatform.content_forms.user_content_type_identifier: "user"

services:
    Ibexa\ContentForms\FieldType\FieldTypeFormMapperDispatcher:
        class: "%ezplatform.content_forms.field_type_form_mapper.dispatcher.class%"

    Ibexa\ContentForms\Form\Type\Content\ContentFieldType:
        class: "%ezplatform.content_forms.field.form_type.class%"
        arguments: ['@Ibexa\ContentForms\FieldType\FieldTypeFormMapperDispatcher']
        tags:
            - { name: form.type, alias: ezplatform_content_forms_content_field }

    # Validators
    Ibexa\AdminUi\Validator\Constraints\FieldTypeValidator:
        class: Ibexa\ContentForms\Validator\Constraints\FieldTypeValidator
        arguments: ['@ibexa.api.service.field_type']
        abstract: true

    Ibexa\ContentForms\Validator\Constraints\PasswordValidator:
        arguments:
            $userService: '@ibexa.api.service.user'
        tags:
            - { name: validator.constraint_validator }

    Ibexa\ContentForms\Validator\Constraints\UserAccountPasswordValidator:
        arguments:
            $userService: '@ibexa.api.service.user'
        tags:
            - { name: validator.constraint_validator }

    Ibexa\ContentForms\Validator\Constraints\FieldValueValidator:
        parent: Ibexa\AdminUi\Validator\Constraints\FieldTypeValidator
        class: "%ezplatform.content_forms.validator.field_value.class%"
        tags:
            - { name: validator.constraint_validator, alias: ezplatform.content_forms.validator.field_value }

    # Action dispatchers
    Ibexa\ContentForms\Form\ActionDispatcher\AbstractActionDispatcher:
        class: "%ezplatform.content_forms.action_dispatcher.base.class%"
        abstract: true
        calls:
            - [setEventDispatcher, ["@event_dispatcher"]]

    Ibexa\ContentForms\Form\ActionDispatcher\ContentDispatcher:
        class: "%ezplatform.content_forms.action_dispatcher.content.class%"
        parent: Ibexa\ContentForms\Form\ActionDispatcher\AbstractActionDispatcher

    Ibexa\ContentForms\Form\ActionDispatcher\UserDispatcher:
        class: "%ezplatform.content_forms.action_dispatcher.user.class%"
        parent: Ibexa\ContentForms\Form\ActionDispatcher\AbstractActionDispatcher

    # Form processors
    Ibexa\ContentForms\Form\Processor\ContentFormProcessor:
        class: '%ezplatform.content_forms.form_processor.content.class%'
        arguments:
            - '@ibexa.api.service.content'
            - '@ibexa.api.service.location'
            - '@router'
        tags:
            - { name: kernel.event_subscriber }

    Ibexa\ContentForms\Form\Processor\User\UserCreateFormProcessor:
        class: "%ezplatform.content_forms.form_processor.user_create.class%"
        arguments:
            - '@ibexa.api.service.user'
            - '@router'
        tags:
            - { name: kernel.event_subscriber }

    Ibexa\ContentForms\Form\Processor\User\UserUpdateFormProcessor:
        class: "%ezplatform.content_forms.form_processor.user_update.class%"
        arguments:
            - '@ibexa.api.service.user'
            - '@ibexa.api.service.content'
            - '@router'
        tags:
            - { name: kernel.event_subscriber }

    Ibexa\ContentForms\Form\Processor\User\UserCancelFormProcessor:
        class: "%ezplatform.content_forms.form_processor.user_cancel.class%"
        arguments:
            - '@router'
        tags:
            - { name: kernel.event_subscriber }

    Ibexa\ContentForms\Form\Processor\SystemUrlRedirectProcessor:
        autowire: true
        autoconfigure: true

    # Controllers
    Ibexa\Bundle\ContentForms\Controller\ContentEditController:
        public: true
        class: "%ezplatform.content_forms.controller.content_edit.class%"
        arguments:
            - '@ibexa.api.service.content_type'
            - '@ibexa.api.service.content'
            - '@Ibexa\ContentForms\Form\ActionDispatcher\ContentDispatcher'
        parent: Ibexa\Core\MVC\Symfony\Controller\Controller
        tags:
              - { name: controller.service_arguments }

    Ibexa\Bundle\ContentForms\Controller\UserController:
        class: "%ezplatform.content_forms.controller.user.class%"
        arguments:
            - '@ibexa.api.service.content_type'
            - '@ibexa.api.service.user'
            - '@ibexa.api.service.location'
            - '@ibexa.api.service.language'
            - '@Ibexa\ContentForms\Form\ActionDispatcher\UserDispatcher'
            - '@Ibexa\Contracts\Core\Repository\PermissionResolver'
            - '@Ibexa\Core\MVC\Symfony\Locale\UserLanguagePreferenceProvider'
        parent: Ibexa\Core\MVC\Symfony\Controller\Controller
        tags:
              - { name: controller.service_arguments }

    ibexa_content_edit:
        alias: Ibexa\Bundle\ContentForms\Controller\ContentEditController
        public: true

    Ibexa\ContentForms\EventListener\ViewTemplatesListener:
        class: "%ezplatform.content_forms.view_templates_listener.class%"
        arguments:
            $configResolver: '@ibexa.config.resolver'
        tags:
            - { name: kernel.event_subscriber }

    Ibexa\ContentForms\ConfigResolver\MaxUploadSize: ~

    Ibexa\Contracts\ContentForms\Content\Form\Provider\GroupedContentFormFieldsProviderInterface:
        '@Ibexa\ContentForms\Content\Form\Provider\GroupedContentFormFieldsProvider'

    Ibexa\ContentForms\Content\Form\Provider\GroupedContentFormFieldsProvider:
        arguments:
            $fieldsGroupsList: '@Ibexa\Core\Helper\FieldsGroups\ArrayTranslatorFieldsGroupsList'
