<?php

/**
 * @copyright Copyright (C) Ibexa AS. All rights reserved.
 * @license For full copyright and license information view LICENSE file distributed with this source code.
 */
declare(strict_types=1);

namespace Ibexa\ContentForms\Validator\Constraints;

use Ibexa\ContentForms\Validator\ValidationErrorsProcessor;
use Ibexa\Contracts\Core\Repository\FieldTypeService;
use Symfony\Component\Validator\ConstraintValidator;

abstract class FieldTypeValidator extends ConstraintValidator
{
    public function __construct(protected readonly FieldTypeService $fieldTypeService)
    {
    }

    /**
     * @param \Ibexa\Contracts\Core\FieldType\ValidationError[] $validationErrors
     */
    protected function processValidationErrors(array $validationErrors): void
    {
        $validationErrorsProcessor = $this->createValidationErrorProcessor();
        $validationErrorsProcessor->processValidationErrors($validationErrors);
    }

    /**
     * Generates the property path an error is meant to.
     * This property path depends on the error target and on the object being validated.
     *
     * Example: "validatorConfiguration[StringLengthValidator][minStringLength]"
     * Defaults to an empty string.
     *
     * @param int $errorIndex index in the error stack (0 indexed)
     * @param string|null $errorTarget error target, generated by API/SPI
     */
    protected function generatePropertyPath(int $errorIndex, ?string $errorTarget): string
    {
        return '';
    }

    private function createValidationErrorProcessor(): ValidationErrorsProcessor
    {
        return new ValidationErrorsProcessor($this->context, function ($index, $target): string {
            return $this->generatePropertyPath($index, $target);
        });
    }
}
