name: CI

on:
    push:
        branches:
            - main
            - '[0-9]+.[0-9]+'
    pull_request: ~

jobs:
    cs-fix:
        name: Run code style check
        runs-on: "ubuntu-22.04"
        strategy:
            matrix:
                php:
                    - '8.1'
        steps:
            - uses: actions/checkout@v5

            - uses: ibexa/gh-workflows/actions/setup-composer-root-version@main

            - uses: ibexa/gh-workflows/actions/composer-install@main
              with:
                  gh-client-id: ${{ secrets.AUTOMATION_CLIENT_ID }}
                  gh-client-secret: ${{ secrets.AUTOMATION_CLIENT_SECRET }}
                  satis-network-key: ${{ secrets.SATIS_NETWORK_KEY }}
                  satis-network-token: ${{ secrets.SATIS_NETWORK_TOKEN }}

            - name: Run code style check
              run: composer run-script check-cs -- --format=checkstyle | cs2pr

    tests:
        name: Unit tests & PHPStan static analysis
        runs-on: "ubuntu-22.04"
        timeout-minutes: 15

        strategy:
            fail-fast: false
            matrix:
                php:
                    - '7.4'
                    - '8.3'
                    - '8.4'

        steps:
            - uses: actions/checkout@v5

            - uses: ibexa/gh-workflows/actions/setup-composer-root-version@main

            - uses: ibexa/gh-workflows/actions/composer-install@main
              with:
                  gh-client-id: ${{ secrets.AUTOMATION_CLIENT_ID }}
                  gh-client-secret: ${{ secrets.AUTOMATION_CLIENT_SECRET }}
                  satis-network-key: ${{ secrets.SATIS_NETWORK_KEY }}
                  satis-network-token: ${{ secrets.SATIS_NETWORK_TOKEN }}

            - name: Setup problem matchers for PHPUnit
              run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

            - name: Run unit test suite
              run: composer test

            - name: Run PHPStan analysis
              run: composer run-script phpstan

    integration-tests:
        name: Runs integration tests
        runs-on: "ubuntu-22.04"
        needs: tests
        timeout-minutes: 15

        strategy:
            fail-fast: false
            matrix:
                php:
                    - '7.4'
                    - '8.3'
                    - '8.4'

        steps:
            - uses: actions/checkout@v5

            - uses: ibexa/gh-workflows/actions/setup-composer-root-version@main

            - uses: ibexa/gh-workflows/actions/composer-install@main
              with:
                  gh-client-id: ${{ secrets.AUTOMATION_CLIENT_ID }}
                  gh-client-secret: ${{ secrets.AUTOMATION_CLIENT_SECRET }}
                  satis-network-key: ${{ secrets.SATIS_NETWORK_KEY }}
                  satis-network-token: ${{ secrets.SATIS_NETWORK_TOKEN }}

            - name: Setup problem matchers for PHPUnit
              run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

            - name: Run unit test suite
              run: composer run-script test-integration
